"""empty message

Revision ID: 41f65b7cad3e
Revises: 540df136f870
Create Date: 2020-05-16 14:51:43.952523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f65b7cad3e'
down_revision = '540df136f870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=200), nullable=False))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('upcoming_shows', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('artist_image_link', sa.String(length=500), nullable=False))
    op.add_column('show', sa.Column('artist_name', sa.String(), nullable=False))
    op.add_column('show', sa.Column('venue_name', sa.String(), nullable=False))
    op.add_column('venue', sa.Column('past_shows', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=200), nullable=False))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('venue', sa.Column('upcoming_shows', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.drop_column('venue', 'seeking_status')
    op.drop_column('venue', 'seeking_msg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_msg', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('seeking_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'upcoming_shows_count')
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'past_shows_count')
    op.drop_column('venue', 'past_shows')
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'artist_name')
    op.drop_column('show', 'artist_image_link')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'past_shows')
    # ### end Alembic commands ###
