"""empty message

Revision ID: 540df136f870
Revises: 71f08b1cea13
Create Date: 2020-05-16 07:47:18.345857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540df136f870'
down_revision = '71f08b1cea13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venuelocation',
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_foreign_key(None, 'venue', 'venuelocation', ['city'], ['city'])
    op.drop_column('venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_table('venuelocation')
    # ### end Alembic commands ###
