"""empty message

Revision ID: 604636dff7b1
Revises: b9642d8f9ee9
Create Date: 2020-06-04 19:03:41.356479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604636dff7b1'
down_revision = 'b9642d8f9ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('artist', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('artist', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('show', 'artist_name')
    op.drop_column('show', 'artist_image_link')
    op.drop_column('show', 'venue_name')
    op.alter_column('venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venue', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('show', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('artist', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('artist', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('artist', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
